config/routes.rb
Rails.application.routes.draw do

  scope '/api/v1' do
    resources :artists, defaults: {format: 'json'}
    resources :albums, defaults: {format: 'json'}
    resources :groups, defaults: {format: 'json'}
  end

  root to: 'artists#index'
  get "*path", to: 'artists#index', via: :all
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/album.rb
class Album < ActiveRecord::Base
  enum release_date_accuracy: {
    YEAR: 0,
    MONTH: 1,
    DAY: 2
  }
end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /places
  # GET /places.json
  def index
    # @albums = Album.order(created_at: :asc).reverse_order.limit(10).reverse
    @albums = Album.order(created_at: :asc)
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :notes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /places
  # GET /places.json
  def index
    # @artists = Artist.order(created_at: :asc).reverse_order.limit(10).reverse
    @artists = Artist.order(created_at: :asc)
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:first_name, :last_name, :notes)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /groups
  # GET /groups.json
  def index
    # @groups = Group.order(created_at: :asc).reverse_order.limit(10).reverse
    @groups = Group.order(created_at: :asc)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :notes)
    end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/albums/delete.html.erb
<h1>Albums#delete</h1>
<p>Find me in app/views/albums/delete.html.erb</p>

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/index.html.erb
<h1>Albums#index</h1>
<p>Find me in app/views/albums/index.html.erb</p>

app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/artists/delete.html.erb
<h1>Artists#delete</h1>
<p>Find me in app/views/artists/delete.html.erb</p>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <title>Soultrust Music Database Rails</title>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-smart-table/2.1.4/smart-table.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ui-view></ui-view>



</body>
</html>